// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn6Z5oyK9mBHYQVFELZ0xh-PpJlxJgvQg',
    appId: '1:42849205898:web:6482db0ad2ff22ab983773',
    messagingSenderId: '42849205898',
    projectId: 'chat-app-8f2ec',
    authDomain: 'chat-app-8f2ec.firebaseapp.com',
    storageBucket: 'chat-app-8f2ec.appspot.com',
    measurementId: 'G-6FLL0F3VNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPSuCLCqD4aFxy6yzJW5SmKXSRmRAX1N4',
    appId: '1:42849205898:android:5e8f622719e61776983773',
    messagingSenderId: '42849205898',
    projectId: 'chat-app-8f2ec',
    storageBucket: 'chat-app-8f2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsVQGnQ8B5rfTdVDimEx0Tuw7RX_hZ6HI',
    appId: '1:42849205898:ios:e642a1b0afbb8dd6983773',
    messagingSenderId: '42849205898',
    projectId: 'chat-app-8f2ec',
    storageBucket: 'chat-app-8f2ec.appspot.com',
    androidClientId: '42849205898-ip22k7i0n2e98bal1fjt5501r69pavso.apps.googleusercontent.com',
    iosClientId: '42849205898-9niib861elqamde468clr13r7vf4r5j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsVQGnQ8B5rfTdVDimEx0Tuw7RX_hZ6HI',
    appId: '1:42849205898:ios:e642a1b0afbb8dd6983773',
    messagingSenderId: '42849205898',
    projectId: 'chat-app-8f2ec',
    storageBucket: 'chat-app-8f2ec.appspot.com',
    androidClientId: '42849205898-ip22k7i0n2e98bal1fjt5501r69pavso.apps.googleusercontent.com',
    iosClientId: '42849205898-9niib861elqamde468clr13r7vf4r5j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn6Z5oyK9mBHYQVFELZ0xh-PpJlxJgvQg',
    appId: '1:42849205898:web:d9a951c53adced7e983773',
    messagingSenderId: '42849205898',
    projectId: 'chat-app-8f2ec',
    authDomain: 'chat-app-8f2ec.firebaseapp.com',
    storageBucket: 'chat-app-8f2ec.appspot.com',
    measurementId: 'G-CJFC9S93TM',
  );

}